### ISSUE TITLE
Support for Polymer 1.x dom-bind

### ISSUE THREAD

**Issue by tomalec** [PolymerElements/test-fixture#24]
I'm not sure in which repo should I post issues. 
_clone of https://github.com/Polymer/test-fixture/issues/17_

Is there any way to use data binding as described at https://github.com/Polymer/test-fixture#data-bound-templates with Polymer 1.x?

Given example fails due to lack of stamp method:

was given a model to stamp, but the template is not of a bindable type

**Comment by tomalec** [comment]
What is even worse
not only data binding fails
```html
<test-fixture id="dom-bind-fixture">
    <template is="dom-bind">
        <h1>{{greeting}}</h2>
    </template>
</test-fixture>
<script>
    // ...
   var bound = fixture('dom-bind-fixture', {greeting: 'ohai thurr'});
</script>
```
but also basic stamping does not work in IE11, Edge:
```html
<test-fixture id="dom-bind-fixture">
    <template>
        <h1>outside dom-bind</h1>
        <template is="dom-bind">
            <h2 id="dom-bind-internals">inside dom-bind</h2>
        </template>
    </template>
</test-fixture>

<script>
    describe('test-fixture', function() {
        before(function() {
            myElContainer = fixture('dom-bind-fixture');
        });
        it('should stamp dom-bind', function(done){
            setTimeout(function(){
                expect(document.getElementById('dom-bind-internals')).to.be.not.null;
                done();
            },1000);
        });
    });
</script>
```

I suspect this may be related to https://github.com/PolymerElements/test-fixture/issues/7

**Comment by cdata** [comment]
Hi, unfortunately nested templates are known to be problematic. This is especially bad in IE, since IE does not have a `template` tag (so `template` contents are not truly inert). You can track this Polymer bug to stay on top of the issue: https://github.com/Polymer/polymer/issues/2495

For now, I would advise that you avoid `test-fixture` for cases when you would normally find yourself nesting `template` tags. This sucks big time, but there is not much we can do about it.
